name: 'infra-repo-update'
description: 'Radxa apt repos management'
inputs:
  test-repo:
    default: false
  token:
    required: true
runs:
  using: "composite"
  steps:
    - name: Query suites info
      id: query
      uses: ./actions/query
    - name: Checkout
      uses: actions/checkout@v4
      with:
        repository: RadxaOS-SDK/rsdk
        path: .tmp/rsdk
    - name: Dispatch workflow
      env:
          GH_TOKEN: ${{ inputs.token }}
      shell: bash
      run: |
        if [[ "${{ inputs.test-repo }}" == "true" ]]
        then
          repo_suffix="-test"
        else
          repo_suffix=""
        fi

        repo_org="$(.tmp/rsdk/src/bin/rsdk config infra.organizations.repository)"
        supported_distros=()
        mapfile -t supported_distros < <(jq -er .[] <<< '${{ steps.query.outputs.suites }}')

        gh extension install mdb/gh-dispatch

        for distro in "${supported_distros[@]}"
        do
          gh dispatch repository \
            --repo "$repo_org/$distro$repo_suffix" \
            --workflow "update.yaml" \
            --event-type "new_package_release"
        done
