name: 'infra-repo-update'
description: 'Radxa apt repos management'
inputs:
  test-repo:
    default: false
  token:
    required: true
runs:
  using: "composite"
  steps:
    - name: Query suites info
      id: query
      uses: AaronDewes/rsdk/.github/actions/query@main
    - name: Checkout
      uses: actions/checkout@v5
      with:
        repository: AaronDewes/rsdk
        path: .tmp/rsdk
    - name: Dispatch workflow
      env:
          GH_TOKEN: ${{ inputs.token }}
      shell: bash
      run: |
        if [[ "${{ inputs.test-repo }}" == "true" ]]
        then
          repo_suffix="-test"
        else
          repo_suffix=""
        fi

        repo_org="$(.tmp/rsdk/src/bin/rsdk config infra.organizations.repository)"
        supported_distros=()
        mapfile -t supported_distros < <(jq -er .[] <<< '${{ steps.query.outputs.suites }}')

        for distro in "${supported_distros[@]}"
        do
          if gh repo view "$repo_org/$distro$repo_suffix" &>/dev/null; then
            gh workflow run .github/workflows/update.yaml --repo "$repo_org/$distro$repo_suffix"
          else
            echo "$repo_org/$distro$repo_suffix does not exist. Skip."
          fi
        done
