name: Reset Test repos
on:
  workflow_dispatch:

permissions: {}

jobs:
  reset-test:
    runs-on: ubuntu-latest
    steps:
      - name: Reset Test repos
        uses: ./.github/actions/infra-repo-update
        with:
          reset: true
          test-repo: true
          token: ${{ secrets.RSDK_APT_REPOSITORY_TOKEN }}
